package mypack;
// Generated Aug 8, 2017 9:46:29 PM by Hibernate Tools 4.3.1



/**
 * Hibersql generated by hbm2java
 */
public class Hibersql  implements java.io.Serializable {


     private String id;
     private String name;
     private String address;

    public Hibersql() {
    }

	
    public Hibersql(String id) {
        this.id = id;
    }
    public Hibersql(String id, String name, String address) {
       this.id = id;
       this.name = name;
       this.address = address;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


